# Rooms where the plugin can be used
rooms:
- '!HnkyiOWbgSMdLAMROq:pink.packageloss.eu'
- '!RPqRTvigdlvWyOwSWz:maunium.net'

# List of user IDs with extra privileges
admins: []

# List of user IDs with fewer privileges
untrusted: []

# maush server url (https://mau.dev/tulir/maush/)
server: https://example.com
